### ISSUE TITLE
URLs have been distributed which are providing deep-linked redirects to the wiki

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#75] opened 2017-01-23 22:49 UTC
The server running {www.,}minnowboard.org currently does a hostname redirect to the server to wiki.minnowboard.org -- this means if someone tries to go to www.minnowboard.org/Random_URL they are redirected to wiki.minnowboard.org/Random_URL.
Those deep-link URLs have been distributed externally.
We need to look at the server logs and Google analytics to find out which URLs are currently being redirected to from {www.,}minnowboard.org and then come up with a strategy for supporting those URL redirects or not.
Specifically, we need to know:
What URLs have been redirected over the last 6-12 months from {www.,}minnowboard.org to wiki.minnowboard.org
How frequently have those URLs been hit
What is the referrer URL for those hits

gitlab issue 229

**Comment by ebrent8** [comment] 2017-02-27 23:10
duplicate of #60 now

**Closed by ebrent8** 2017-02-27 23:10 UTC
