### ISSUE TITLE
tutorial link in header doesn't show tutorial home page when in a tutorial

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#65] opened 2017-01-23 22:14 UTC
While I'm looking at a tutorial, say https://sxc.jf.intel.com/minnow/tutorials/updating_your_firmware if I click on the "Tutorials" link in the header I'd expect to get back to the tutorials home page https://sxc.jf.intel.com/minnow/tutorials but I don't. Nothing happens. If I click on one of the other header links (like "Learn More") and then click on the "Tutorials" link in the header I get where I expected to be.

moving from issue 57 in gitlab

**Comment by ebrent8** [comment] 2017-02-10 18:21
closing and fixed in staging.  duplicate of #12

**Closed by ebrent8** 2017-02-10 18:21 UTC
