### ISSUE TITLE
Control-click doesn't work as expected (open the link in a new tab)

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#79] opened 2017-01-23 23:00 UTC
In Chrome and Intenet Explorer, holding down control and clicking on a link opens that link in a new browser tab. This doesn't work (in general) for links on the stg.minnowboard.org site - links open in the same window when you hold down control and click on the link:
If you control-click on one of the header links it should open in a new tab (but doesn't).
If you're in a tutorial and control-click on the "Explore the board" header link, that should open in a new tab (and doesn't).
There are some cases where control-click does work as expected:
on the "Get a Board" page, if you control-click on the "OS installed" link in the left nav area, a new tab is opened.
in the "Power on" tutorial, if you control-click on the "see this page" link in the components list, a new tab is opened.
@hayatb, we should preserve the expected browser control-click to open a link in a new tab function, yes?

Issue 241 in gitlab

**Comment by juliocri** [comment] 2017-04-18 19:35
@adreanneb I was reviewing this, and the root cause is because the links that you mentioned in the reality are not links, are divs that works as anchors but being a div has not control click actions as same as the proper anchors have....

Mainly all the divs that simulates an anchor are titles or slugs auto generated or are internal references to content in the minnow site, I think we can change them to links, but it will be costly in performance due right now if you make a click on them the application only goes thru the url and change the content to show without reload the page, changing to regular links making click on them the app will need to reload.... are you agree with the change? is currently needed? @ebrent8

**Comment by ebrent8** [comment] 2017-04-18 20:35
I don't think it's worth it to make any costly changes at this point.

**Comment by juliocri** [comment] 2017-04-19 14:55
Agreed, I will close this issue by now.

**Closed by juliocri** 2017-04-19 14:55 UTC
Labels: Dev, Prty_Med
